In [1]:
import numpy as np

s = "book"

In [2]:
s_list = list(s)
s_list

['b', 'o', 'o', 'k']

In [3]:
s_prime = '|' + '|'.join(s_list) + '|'
s_prime

'|b|o|o|k|'

In [4]:
from lps import longest_palindrome_substring_slow as lps_slow


In [5]:
pal = lps_slow(s)

[4. 2. 4. 6. 4. 2. 4. 2. 0.]


In [6]:
pal

2

In [7]:
s = 'abracadabra'

pal = lps_slow(s)

pal

[4. 2. 4. 2. 4. 2. 4. 2. 8. 2. 4. 2. 8. 2. 4. 2. 4. 2. 4. 2. 4. 2. 0.]


3

In [8]:
s = 'racecar'
lps_slow(s)

[ 4.  2.  4.  2.  4.  2. 16.  2.  4.  2.  4.  2.  4.  2.  0.]


7

In [9]:
arr = [4, 2, 4, 6, 4, 2, 4, 2, 0,]

In [10]:
import numpy as np
new_arr = (np.array(arr) -1) /2

In [11]:
new_arr

array([ 1.5,  0.5,  1.5,  2.5,  1.5,  0.5,  1.5,  0.5, -0.5])

In [12]:
new_arr = np.array(new_arr, dtype=np.int)

In [13]:
new_arr

array([1, 0, 1, 2, 1, 0, 1, 0, 0])

In [14]:
new_arr = new_arr[1::2]

In [15]:
new_arr

array([0, 2, 0, 0])

In [16]:
indexes = [index for index, item in enumerate(new_arr) if item == max(new_arr)]

In [17]:
indexes

[1]

In [18]:
new_arr[indexes]

array([2])

In [19]:
s = 'book'

In [21]:
s[1:3]

'oo'