In [1]:
import numpy as np

s = "book"

In [2]:
s_list = list(s)
s_list

['b', 'o', 'o', 'k']

In [3]:
s_prime = '|' + '|'.join(s_list) + '|'
s_prime

'|b|o|o|k|'

In [4]:
from lps import longest_palindrome_substring_slow as lps_slow
from lps import longest_palindrome_substring_manacher as lps_manacher

In [5]:
pal = lps_slow(s)

[4. 2. 4. 6. 4. 2. 4. 2. 0.]
3 2


In [6]:
pal

['oo']

In [7]:
pal2 = lps_manacher('book')
pal2

[2. 0. 0. 3. 0. 0. 0. 1. 0.]
3 3


['o']

In [8]:
s = 'book'
s_prime = '|b|o|o|k|'

centre = 3
radius = 2
s_prime[centre - radius + 1: centre + radius + 1]

'|o|o'

In [9]:
s = 'abracadabra'

pal = lps_slow(s)
pal

[4. 2. 4. 2. 4. 2. 4. 2. 8. 2. 4. 2. 8. 2. 4. 2. 4. 2. 4. 2. 4. 2. 0.]
8 3
12 3


['aca', 'ada']

In [10]:


pal2 = lps_manacher('abracadabra')

[2. 0. 0. 1. 2. 1. 2. 1. 4. 1. 2. 1. 4. 1. 2. 1. 2. 1. 2. 1. 2. 1. 0.]
8 4
12 4


In [11]:
pal2

['ac', 'ad']

In [12]:
s = 'racecar'
lps_slow(s)

[ 4.  2.  4.  2.  4.  2. 16.  2.  4.  2.  4.  2.  4.  2.  0.]
6 7


['racecar']

In [13]:
lps_manacher('racecar')

[2. 0. 0. 1. 2. 1. 8. 1. 2. 1. 0. 0. 2. 0. 0.]
6 8


['acec']

In [14]:
s = 'racecar'
s_prime = '|' + '|'.join(list(s)) + '|'

centre = 6
radius = 7
s_prime[centre - radius + 1: centre + radius + 1]

'|r|a|c|e|c|a|r'

In [15]:
arr = [4, 2, 4, 6, 4, 2, 4, 2, 0,]

In [16]:
import numpy as np
new_arr = (np.array(arr) -1) /2

In [17]:
new_arr

array([ 1.5,  0.5,  1.5,  2.5,  1.5,  0.5,  1.5,  0.5, -0.5])

In [18]:
new_arr = np.array(new_arr, dtype=np.int)

In [19]:
new_arr

array([1, 0, 1, 2, 1, 0, 1, 0, 0])

In [20]:
new_arr = new_arr[1::2]

In [21]:
new_arr

array([0, 2, 0, 0])

In [22]:
indexes = [index for index, item in enumerate(new_arr) if item == max(new_arr)]

In [23]:
indexes

[1]

In [24]:
new_arr[indexes]

array([2])

In [25]:
s = 'book'

In [26]:
s[1:3]

'oo'